[workspace]
members = ["chesslib"]

[package]
name = "chessapp"
version = "0.1.0"
edition = "2024"

[dependencies]
chesslib = { path = "chesslib" }
macroquad = { version = "0.4.*", features = ["audio"] }
thiserror = "2.0.*"
anyhow = "1.0.*"
